# Generated by Django 5.0.6 on 2024-07-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0002_rename_department_inform_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inform',
            options={'ordering': ('-create_time',)},
        ),
    ]
