# Generated by Django 5.0.6 on 2024-07-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0003_rename_info_oadepartment_intro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oadepartment',
            options={'ordering': ('-id',)},
        ),
    ]
