# Generated by Django 5.0.6 on 2024-07-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inform',
            old_name='department',
            new_name='departments',
        ),
    ]
