# Generated by Django 5.0.6 on 2024-06-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absent',
            old_name='create_date',
            new_name='create_time',
        ),
    ]
