# Generated by Django 5.0.6 on 2024-07-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0002_rename_create_date_absent_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absent',
            options={'ordering': ('-create_time',)},
        ),
    ]
