# Generated by Django 5.0.6 on 2024-06-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0002_oadepartment_oauser_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oadepartment',
            old_name='info',
            new_name='intro',
        ),
    ]
