# Generated by Django 5.0.6 on 2024-07-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0004_alter_oadepartment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oadepartment',
            options={},
        ),
    ]
